# This file is a template, and might need editing before it works on
# your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
---
image: "node:latest"

cache:
  key: "$CI_BUILD_STAGE_$CI_BUILD_REF_NAME_02"
  paths:
    - node_modules/
    - yarn-cache/

stages:
  - build-dev
  - build-prod
  - deploy

before_script:
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
  - apt update && apt install yarn
  - yarn

lint:
  stage: build-dev
  script:
    - npm run lint
  except:
    - develop
    - master

build-dev:
  stage: build-dev
  artifacts:
    paths:
      - public/
      - firebase/
  script:
    - time npm run build-rules
    - time npm run build-dev
  only:
    - develop
  except: 
    - master

build-prod:
  stage: build-prod
  artifacts:
    paths:
      - public/
      - firebase/
  script:
    - time npm run build-rules
    - time npm run build-prod
  only:
    - master

deploy_staging:
  stage: deploy
  environment: staging
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev rubygems
    - gem install dpl
  dependencies:
    - build-dev
  only:
    - develop
  script:
    - 'dpl --skip_cleanup --provider=firebase
    --token=$FIREBASE_DEPLOY_STAGING --project=treesradio-staging'

deploy_production:
  stage: deploy
  environment: production
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev rubygems
    - gem install dpl
  dependencies:
    - build-prod
  only:
    - master
  script:
    - 'dpl --skip_cleanup --provider=firebase
    --token=$FIREBASE_DEPLOY_PROD --project=treesradio-live'
