# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:7

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
#services:
#  - mysql:latest
#  - redis:latest
#  - postgres:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  key: "$CI_BUILD_STAGE/$CI_BUILD_REF_NAME/02"
  paths:
  - node_modules/
  - yarn-cache/

stages:
  - build
  - deploy

before_script:
      - mkdir -p /root/
      - mkdir -p yarn-cache
      - curl -o- -L https://yarnpkg.com/install.sh | bash
      - source ~/.bashrc
      - ln -s $PWD/yarn-cache /root/.yarn-cache
      - yarn

lint:
  stage: build
  script:
    - npm run lint

build:
  stage: build
  artifacts:
    paths:
      - public/
  script:
    - time npm run bolt-compile
    - time npm run build-app

deploy_staging:
  stage: deploy
  environment: staging
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev rubygems
    - gem install dpl
  dependencies:
    - build
  only:
   - develop
  script:
    - dpl --skip_cleanup --provider=firebase --token=$FIREBASE_DEPLOY_STAGING --project=treesradio-staging
