# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:8

cache:
  key: "$CI_BUILD_STAGE_$CI_BUILD_REF_NAME_02"
  paths:
  - node_modules/
  - yarn-cache/

stages:
  - build
  - deploy

before_script:
      - mkdir -p /root/
      - mkdir -p yarn-cache
      - curl -o- -L https://yarnpkg.com/install.sh | bash
      - source ~/.bashrc
      - ln -s $PWD/yarn-cache /root/.yarn-cache
      - yarn

lint:
  stage: build
  script:
    - npm run lint

build:
  stage: build
  artifacts:
    paths:
      - public/
      - firebase/
  script:
    - time npm run build-rules
    - time npm run build-app

deploy_staging:
  stage: deploy
  environment: staging
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev rubygems
    - gem install dpl
  dependencies:
    - build
  only:
    - develop
  script:
    - dpl --skip_cleanup --provider=firebase --token=$FIREBASE_DEPLOY_STAGING --project=treesradio-staging

deploy_production:
  stage: deploy
  environment: production
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev rubygems
    - gem install dpl
  dependencies:
    - build
  only:
    - master
  script:
    - dpl --skip_cleanup --provider=firebase --token=$FIREBASE_DEPLOY_PROD --project=treesradio-live
